name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Frontend build
        run: |
          cd frontend
          npm i --save-dev @types/node
          npm install
          npm run build

      - name: Backend build
        run: |
          cd ../cop4331-5
          npm install

  deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Deploy Application
      #   run: |
      #     scp -r ./frontend/dist/ root@cop4331-5.com:/var/www/html/
      #     scp -r ./ root@cop4331-5.com:/var/cardsServer/
      #     ssh root@cop4331-5.com 'sudo systemctl restart express-server
