name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust to the branch you use
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1' 
          cache: 'npm'

      - name: Frontend build
        run: |
          cd frontend
          npm i --save-dev @types/node
          npm install
          npm run build
          cd ..

      - name: Backend build
        run: |
          npm install
          ssh root@cop4331-5.com 'sudo systemctl restart express-server
  # deploy:
  #   needs: build
  #   runs-on: self-hosted
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Deploy Application
  #       run: |
  #         scp -r ./frontend/dist/ root@cop4331-5.com:/var/www/html/
  #         scp -r ./ root@cop4331-5.com:/var/cardsServer/
  #         ssh root@cop4331-5.com 'sudo systemctl restart express-server
